### ISSUE TITLE
No tray icon in forced wayland mode

### ISSUE THREAD

**Issue by Apacelus** [flathub/xyz.armcord.ArmCord#7]
This does not happen with the AppImage version.

When I force the app to run under Wayland, the tray icon doesnt show up. The tray icon does work for other wayland flatpak apps(though those are not electron apps)

**Comment by orowith2os** [comment]
I know what the cause is, ArmCord is missing a talk permission. Find me the common talk names for those apps and I'll add the fix.

**Comment by orowith2os** [comment]
Try the builds over at https://github.com/flathub/xyz.armcord.ArmCord/pull/8

**Comment by orowith2os** [comment]
I can't really solve this, so.... wait for a new tray spec or use it through Xwayland, ig.

**Comment by orowith2os** [comment]
Fixed in #10, which works surprisingly well.

**Comment by Kyr4l** [comment]
![image](https://user-images.githubusercontent.com/24955106/231450997-5be4b834-13fc-43bb-880d-565aa8d7f054.png)
not working for me

**Comment by Apacelus** [comment]
Works for me, allthough with this issue https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/283

**Comment by Kyr4l** [comment]
> 

well i use KDE Plasma

**Comment by orowith2os** [comment]
The tray icon won't work in forced Wayland mode because it's using the X11 tray icon. As you can probably tell, the X11 tray icon won't work on Wayland because it's not a *Wayland* tray icon (nor is there one).

I knew people would complain about it, so I didn't enable it by default.

You can revert to a "broken" build (using a newer version of Electron with no screen casting) for the "proper" tray icon.
